// Code generated by protoc-gen-go. DO NOT EDIT.
// source: platform/grpc/user/fiber.proto

package user

import (
	context "context"
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion3 // please upgrade the proto package

// The request message
type RequestTokenValidation struct {
	Token                string   `protobuf:"bytes,1,opt,name=token,proto3" json:"token,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestTokenValidation) Reset()         { *m = RequestTokenValidation{} }
func (m *RequestTokenValidation) String() string { return proto.CompactTextString(m) }
func (*RequestTokenValidation) ProtoMessage()    {}
func (*RequestTokenValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4479d21a53a61bd, []int{0}
}

func (m *RequestTokenValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestTokenValidation.Unmarshal(m, b)
}
func (m *RequestTokenValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestTokenValidation.Marshal(b, m, deterministic)
}
func (m *RequestTokenValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestTokenValidation.Merge(m, src)
}
func (m *RequestTokenValidation) XXX_Size() int {
	return xxx_messageInfo_RequestTokenValidation.Size(m)
}
func (m *RequestTokenValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestTokenValidation.DiscardUnknown(m)
}

var xxx_messageInfo_RequestTokenValidation proto.InternalMessageInfo

func (m *RequestTokenValidation) GetToken() string {
	if m != nil {
		return m.Token
	}
	return ""
}

// The response message
type ResponseTokenValidation struct {
	OldId                int32    `protobuf:"varint,1,opt,name=oldId,proto3" json:"oldId,omitempty"`
	MobilePhoneNumber    string   `protobuf:"bytes,2,opt,name=mobilePhoneNumber,proto3" json:"mobilePhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseTokenValidation) Reset()         { *m = ResponseTokenValidation{} }
func (m *ResponseTokenValidation) String() string { return proto.CompactTextString(m) }
func (*ResponseTokenValidation) ProtoMessage()    {}
func (*ResponseTokenValidation) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4479d21a53a61bd, []int{1}
}

func (m *ResponseTokenValidation) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseTokenValidation.Unmarshal(m, b)
}
func (m *ResponseTokenValidation) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseTokenValidation.Marshal(b, m, deterministic)
}
func (m *ResponseTokenValidation) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseTokenValidation.Merge(m, src)
}
func (m *ResponseTokenValidation) XXX_Size() int {
	return xxx_messageInfo_ResponseTokenValidation.Size(m)
}
func (m *ResponseTokenValidation) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseTokenValidation.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseTokenValidation proto.InternalMessageInfo

func (m *ResponseTokenValidation) GetOldId() int32 {
	if m != nil {
		return m.OldId
	}
	return 0
}

func (m *ResponseTokenValidation) GetMobilePhoneNumber() string {
	if m != nil {
		return m.MobilePhoneNumber
	}
	return ""
}

type RequestGetUser struct {
	MobilePhoneNumber    string   `protobuf:"bytes,1,opt,name=mobilePhoneNumber,proto3" json:"mobilePhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGetUser) Reset()         { *m = RequestGetUser{} }
func (m *RequestGetUser) String() string { return proto.CompactTextString(m) }
func (*RequestGetUser) ProtoMessage()    {}
func (*RequestGetUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4479d21a53a61bd, []int{2}
}

func (m *RequestGetUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGetUser.Unmarshal(m, b)
}
func (m *RequestGetUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGetUser.Marshal(b, m, deterministic)
}
func (m *RequestGetUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGetUser.Merge(m, src)
}
func (m *RequestGetUser) XXX_Size() int {
	return xxx_messageInfo_RequestGetUser.Size(m)
}
func (m *RequestGetUser) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGetUser.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGetUser proto.InternalMessageInfo

func (m *RequestGetUser) GetMobilePhoneNumber() string {
	if m != nil {
		return m.MobilePhoneNumber
	}
	return ""
}

type ResponseGetUser struct {
	Id                   int64         `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	MobilePhoneNumber    string        `protobuf:"bytes,2,opt,name=mobilePhoneNumber,proto3" json:"mobilePhoneNumber,omitempty"`
	Email                string        `protobuf:"bytes,3,opt,name=email,proto3" json:"email,omitempty"`
	ReferralCode         string        `protobuf:"bytes,4,opt,name=referralCode,proto3" json:"referralCode,omitempty"`
	FullName             string        `protobuf:"bytes,5,opt,name=fullName,proto3" json:"fullName,omitempty"`
	OttocashLink         bool          `protobuf:"varint,6,opt,name=ottocashLink,proto3" json:"ottocashLink,omitempty"`
	OttocashCustomerId   int64         `protobuf:"varint,7,opt,name=ottocashCustomerId,proto3" json:"ottocashCustomerId,omitempty"`
	OttocashInfo         *OttocashInfo `protobuf:"bytes,8,opt,name=ottocashInfo,proto3" json:"ottocashInfo,omitempty"`
	FirebaseToken        string        `protobuf:"bytes,9,opt,name=firebaseToken,proto3" json:"firebaseToken,omitempty"`
	XXX_NoUnkeyedLiteral struct{}      `json:"-"`
	XXX_unrecognized     []byte        `json:"-"`
	XXX_sizecache        int32         `json:"-"`
}

func (m *ResponseGetUser) Reset()         { *m = ResponseGetUser{} }
func (m *ResponseGetUser) String() string { return proto.CompactTextString(m) }
func (*ResponseGetUser) ProtoMessage()    {}
func (*ResponseGetUser) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4479d21a53a61bd, []int{3}
}

func (m *ResponseGetUser) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseGetUser.Unmarshal(m, b)
}
func (m *ResponseGetUser) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseGetUser.Marshal(b, m, deterministic)
}
func (m *ResponseGetUser) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseGetUser.Merge(m, src)
}
func (m *ResponseGetUser) XXX_Size() int {
	return xxx_messageInfo_ResponseGetUser.Size(m)
}
func (m *ResponseGetUser) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseGetUser.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseGetUser proto.InternalMessageInfo

func (m *ResponseGetUser) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseGetUser) GetMobilePhoneNumber() string {
	if m != nil {
		return m.MobilePhoneNumber
	}
	return ""
}

func (m *ResponseGetUser) GetEmail() string {
	if m != nil {
		return m.Email
	}
	return ""
}

func (m *ResponseGetUser) GetReferralCode() string {
	if m != nil {
		return m.ReferralCode
	}
	return ""
}

func (m *ResponseGetUser) GetFullName() string {
	if m != nil {
		return m.FullName
	}
	return ""
}

func (m *ResponseGetUser) GetOttocashLink() bool {
	if m != nil {
		return m.OttocashLink
	}
	return false
}

func (m *ResponseGetUser) GetOttocashCustomerId() int64 {
	if m != nil {
		return m.OttocashCustomerId
	}
	return 0
}

func (m *ResponseGetUser) GetOttocashInfo() *OttocashInfo {
	if m != nil {
		return m.OttocashInfo
	}
	return nil
}

func (m *ResponseGetUser) GetFirebaseToken() string {
	if m != nil {
		return m.FirebaseToken
	}
	return ""
}

type OttocashInfo struct {
	EmoneyBalance        int64    `protobuf:"varint,1,opt,name=emoneyBalance,proto3" json:"emoneyBalance,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *OttocashInfo) Reset()         { *m = OttocashInfo{} }
func (m *OttocashInfo) String() string { return proto.CompactTextString(m) }
func (*OttocashInfo) ProtoMessage()    {}
func (*OttocashInfo) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4479d21a53a61bd, []int{4}
}

func (m *OttocashInfo) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_OttocashInfo.Unmarshal(m, b)
}
func (m *OttocashInfo) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_OttocashInfo.Marshal(b, m, deterministic)
}
func (m *OttocashInfo) XXX_Merge(src proto.Message) {
	xxx_messageInfo_OttocashInfo.Merge(m, src)
}
func (m *OttocashInfo) XXX_Size() int {
	return xxx_messageInfo_OttocashInfo.Size(m)
}
func (m *OttocashInfo) XXX_DiscardUnknown() {
	xxx_messageInfo_OttocashInfo.DiscardUnknown(m)
}

var xxx_messageInfo_OttocashInfo proto.InternalMessageInfo

func (m *OttocashInfo) GetEmoneyBalance() int64 {
	if m != nil {
		return m.EmoneyBalance
	}
	return 0
}

type RequestGetCivilRegistry struct {
	MobilePhoneNumber    string   `protobuf:"bytes,1,opt,name=mobilePhoneNumber,proto3" json:"mobilePhoneNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RequestGetCivilRegistry) Reset()         { *m = RequestGetCivilRegistry{} }
func (m *RequestGetCivilRegistry) String() string { return proto.CompactTextString(m) }
func (*RequestGetCivilRegistry) ProtoMessage()    {}
func (*RequestGetCivilRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4479d21a53a61bd, []int{5}
}

func (m *RequestGetCivilRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RequestGetCivilRegistry.Unmarshal(m, b)
}
func (m *RequestGetCivilRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RequestGetCivilRegistry.Marshal(b, m, deterministic)
}
func (m *RequestGetCivilRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RequestGetCivilRegistry.Merge(m, src)
}
func (m *RequestGetCivilRegistry) XXX_Size() int {
	return xxx_messageInfo_RequestGetCivilRegistry.Size(m)
}
func (m *RequestGetCivilRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_RequestGetCivilRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_RequestGetCivilRegistry proto.InternalMessageInfo

func (m *RequestGetCivilRegistry) GetMobilePhoneNumber() string {
	if m != nil {
		return m.MobilePhoneNumber
	}
	return ""
}

type ResponseGetCivilRegistry struct {
	Id                   int64    `protobuf:"varint,1,opt,name=id,proto3" json:"id,omitempty"`
	IdCardName           string   `protobuf:"bytes,2,opt,name=idCardName,proto3" json:"idCardName,omitempty"`
	Gender               string   `protobuf:"bytes,3,opt,name=gender,proto3" json:"gender,omitempty"`
	Religion             string   `protobuf:"bytes,4,opt,name=religion,proto3" json:"religion,omitempty"`
	DateOfBirth          string   `protobuf:"bytes,5,opt,name=dateOfBirth,proto3" json:"dateOfBirth,omitempty"`
	Address              string   `protobuf:"bytes,6,opt,name=address,proto3" json:"address,omitempty"`
	PlaceOfBirth         string   `protobuf:"bytes,7,opt,name=placeOfBirth,proto3" json:"placeOfBirth,omitempty"`
	Province             string   `protobuf:"bytes,8,opt,name=province,proto3" json:"province,omitempty"`
	BloodGroup           string   `protobuf:"bytes,9,opt,name=bloodGroup,proto3" json:"bloodGroup,omitempty"`
	Rt                   string   `protobuf:"bytes,10,opt,name=rt,proto3" json:"rt,omitempty"`
	Rw                   string   `protobuf:"bytes,11,opt,name=rw,proto3" json:"rw,omitempty"`
	City                 string   `protobuf:"bytes,12,opt,name=city,proto3" json:"city,omitempty"`
	Kelurahan            string   `protobuf:"bytes,13,opt,name=kelurahan,proto3" json:"kelurahan,omitempty"`
	District             string   `protobuf:"bytes,14,opt,name=district,proto3" json:"district,omitempty"`
	MarriageStatus       string   `protobuf:"bytes,15,opt,name=marriageStatus,proto3" json:"marriageStatus,omitempty"`
	IdCardNumber         string   `protobuf:"bytes,16,opt,name=idCardNumber,proto3" json:"idCardNumber,omitempty"`
	Occupation           string   `protobuf:"bytes,17,opt,name=occupation,proto3" json:"occupation,omitempty"`
	Citizenship          string   `protobuf:"bytes,18,opt,name=citizenship,proto3" json:"citizenship,omitempty"`
	IdCardImage          string   `protobuf:"bytes,19,opt,name=idCardImage,proto3" json:"idCardImage,omitempty"`
	SignatureImage       string   `protobuf:"bytes,20,opt,name=signatureImage,proto3" json:"signatureImage,omitempty"`
	SelfieImage          string   `protobuf:"bytes,21,opt,name=selfieImage,proto3" json:"selfieImage,omitempty"`
	Version              int64    `protobuf:"varint,22,opt,name=version,proto3" json:"version,omitempty"`
	Job                  string   `protobuf:"bytes,23,opt,name=job,proto3" json:"job,omitempty"`
	JobDescription       string   `protobuf:"bytes,24,opt,name=jobDescription,proto3" json:"jobDescription,omitempty"`
	Feature              string   `protobuf:"bytes,25,opt,name=feature,proto3" json:"feature,omitempty"`
	Product              string   `protobuf:"bytes,26,opt,name=product,proto3" json:"product,omitempty"`
	Description          string   `protobuf:"bytes,27,opt,name=description,proto3" json:"description,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ResponseGetCivilRegistry) Reset()         { *m = ResponseGetCivilRegistry{} }
func (m *ResponseGetCivilRegistry) String() string { return proto.CompactTextString(m) }
func (*ResponseGetCivilRegistry) ProtoMessage()    {}
func (*ResponseGetCivilRegistry) Descriptor() ([]byte, []int) {
	return fileDescriptor_d4479d21a53a61bd, []int{6}
}

func (m *ResponseGetCivilRegistry) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ResponseGetCivilRegistry.Unmarshal(m, b)
}
func (m *ResponseGetCivilRegistry) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ResponseGetCivilRegistry.Marshal(b, m, deterministic)
}
func (m *ResponseGetCivilRegistry) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ResponseGetCivilRegistry.Merge(m, src)
}
func (m *ResponseGetCivilRegistry) XXX_Size() int {
	return xxx_messageInfo_ResponseGetCivilRegistry.Size(m)
}
func (m *ResponseGetCivilRegistry) XXX_DiscardUnknown() {
	xxx_messageInfo_ResponseGetCivilRegistry.DiscardUnknown(m)
}

var xxx_messageInfo_ResponseGetCivilRegistry proto.InternalMessageInfo

func (m *ResponseGetCivilRegistry) GetId() int64 {
	if m != nil {
		return m.Id
	}
	return 0
}

func (m *ResponseGetCivilRegistry) GetIdCardName() string {
	if m != nil {
		return m.IdCardName
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetGender() string {
	if m != nil {
		return m.Gender
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetReligion() string {
	if m != nil {
		return m.Religion
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetDateOfBirth() string {
	if m != nil {
		return m.DateOfBirth
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetAddress() string {
	if m != nil {
		return m.Address
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetPlaceOfBirth() string {
	if m != nil {
		return m.PlaceOfBirth
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetProvince() string {
	if m != nil {
		return m.Province
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetBloodGroup() string {
	if m != nil {
		return m.BloodGroup
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetRt() string {
	if m != nil {
		return m.Rt
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetRw() string {
	if m != nil {
		return m.Rw
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetCity() string {
	if m != nil {
		return m.City
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetKelurahan() string {
	if m != nil {
		return m.Kelurahan
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetDistrict() string {
	if m != nil {
		return m.District
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetMarriageStatus() string {
	if m != nil {
		return m.MarriageStatus
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetIdCardNumber() string {
	if m != nil {
		return m.IdCardNumber
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetOccupation() string {
	if m != nil {
		return m.Occupation
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetCitizenship() string {
	if m != nil {
		return m.Citizenship
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetIdCardImage() string {
	if m != nil {
		return m.IdCardImage
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetSignatureImage() string {
	if m != nil {
		return m.SignatureImage
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetSelfieImage() string {
	if m != nil {
		return m.SelfieImage
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetVersion() int64 {
	if m != nil {
		return m.Version
	}
	return 0
}

func (m *ResponseGetCivilRegistry) GetJob() string {
	if m != nil {
		return m.Job
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetJobDescription() string {
	if m != nil {
		return m.JobDescription
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetFeature() string {
	if m != nil {
		return m.Feature
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetProduct() string {
	if m != nil {
		return m.Product
	}
	return ""
}

func (m *ResponseGetCivilRegistry) GetDescription() string {
	if m != nil {
		return m.Description
	}
	return ""
}

func init() {
	proto.RegisterType((*RequestTokenValidation)(nil), "user.RequestTokenValidation")
	proto.RegisterType((*ResponseTokenValidation)(nil), "user.ResponseTokenValidation")
	proto.RegisterType((*RequestGetUser)(nil), "user.RequestGetUser")
	proto.RegisterType((*ResponseGetUser)(nil), "user.ResponseGetUser")
	proto.RegisterType((*OttocashInfo)(nil), "user.OttocashInfo")
	proto.RegisterType((*RequestGetCivilRegistry)(nil), "user.RequestGetCivilRegistry")
	proto.RegisterType((*ResponseGetCivilRegistry)(nil), "user.ResponseGetCivilRegistry")
}

func init() { proto.RegisterFile("platform/grpc/user/fiber.proto", fileDescriptor_d4479d21a53a61bd) }

var fileDescriptor_d4479d21a53a61bd = []byte{
	// 779 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0x94, 0x55, 0xcb, 0x4e, 0x03, 0x37,
	0x14, 0x25, 0x21, 0xe4, 0x61, 0x20, 0x80, 0xcb, 0xc3, 0x4d, 0x01, 0x45, 0x23, 0x54, 0xb1, 0xa8,
	0x82, 0x44, 0xab, 0xaa, 0xab, 0x2e, 0x92, 0x4a, 0x28, 0x52, 0x05, 0xd1, 0xd0, 0x76, 0xd7, 0x85,
	0x33, 0x73, 0x27, 0x31, 0x78, 0xc6, 0x53, 0xdb, 0x03, 0xa5, 0xdf, 0xd4, 0xff, 0xe9, 0x27, 0xf4,
	0x37, 0x2a, 0x3f, 0x86, 0xcc, 0x84, 0x74, 0xc1, 0x26, 0x9a, 0x73, 0xae, 0xef, 0xf1, 0xbd, 0xf7,
	0x38, 0x36, 0xba, 0xc8, 0x39, 0xd5, 0x89, 0x90, 0xe9, 0xcd, 0x42, 0xe6, 0xd1, 0x4d, 0xa1, 0x40,
	0xda, 0x9f, 0x51, 0x2e, 0x85, 0x16, 0xb8, 0x65, 0xbe, 0x83, 0x11, 0x3a, 0x0d, 0xe1, 0x8f, 0x02,
	0x94, 0xfe, 0x45, 0x3c, 0x43, 0xf6, 0x1b, 0xe5, 0x2c, 0xa6, 0x9a, 0x89, 0x0c, 0x1f, 0xa3, 0x1d,
	0x6d, 0x28, 0xd2, 0x18, 0x36, 0xae, 0x7b, 0xa1, 0x03, 0xc1, 0xef, 0xe8, 0x2c, 0x04, 0x95, 0x8b,
	0x4c, 0xc1, 0x86, 0x04, 0xc1, 0xe3, 0x69, 0x6c, 0x13, 0x76, 0x42, 0x07, 0xf0, 0x37, 0xe8, 0x28,
	0x15, 0x73, 0xc6, 0x61, 0xb6, 0x14, 0x19, 0xdc, 0x17, 0xe9, 0x1c, 0x24, 0x69, 0x5a, 0xc9, 0x8f,
	0x81, 0xe0, 0x47, 0xd4, 0xf7, 0xe5, 0xdc, 0x81, 0xfe, 0x55, 0x81, 0xdc, 0x9c, 0xdf, 0xf8, 0xbf,
	0xfc, 0x7f, 0x9a, 0xe8, 0xa0, 0xac, 0xaf, 0x54, 0xe8, 0xa3, 0x26, 0x73, 0x45, 0x6d, 0x87, 0x4d,
	0xf6, 0xc9, 0x8a, 0x4c, 0x57, 0x90, 0x52, 0xc6, 0xc9, 0xb6, 0x1b, 0x83, 0x05, 0x38, 0x40, 0x7b,
	0x12, 0x12, 0x90, 0x92, 0xf2, 0x89, 0x88, 0x81, 0xb4, 0x6c, 0xb0, 0xc6, 0xe1, 0x01, 0xea, 0x26,
	0x05, 0xe7, 0xf7, 0x34, 0x05, 0xb2, 0x63, 0xe3, 0xef, 0xd8, 0xe4, 0x0b, 0xad, 0x45, 0x44, 0xd5,
	0xf2, 0x67, 0x96, 0x3d, 0x93, 0xf6, 0xb0, 0x71, 0xdd, 0x0d, 0x6b, 0x1c, 0x1e, 0x21, 0x5c, 0xe2,
	0x49, 0xa1, 0xb4, 0x48, 0x41, 0x4e, 0x63, 0xd2, 0xb1, 0x7d, 0x6c, 0x88, 0xe0, 0xef, 0x57, 0x9a,
	0xd3, 0x2c, 0x11, 0xa4, 0x3b, 0x6c, 0x5c, 0xef, 0xde, 0xe2, 0x91, 0xf5, 0xfc, 0xa1, 0x12, 0x09,
	0x6b, 0xeb, 0xf0, 0x15, 0xda, 0x4f, 0x98, 0x84, 0x39, 0xf5, 0x96, 0x92, 0x9e, 0x2d, 0xb6, 0x4e,
	0x06, 0xdf, 0xa1, 0xbd, 0x87, 0xb5, 0x2c, 0x48, 0x45, 0x06, 0x6f, 0x63, 0xca, 0x69, 0x16, 0x81,
	0x1f, 0x70, 0x9d, 0x0c, 0xee, 0xcc, 0x71, 0x29, 0xfd, 0x9c, 0xb0, 0x17, 0xc6, 0x43, 0x58, 0x30,
	0xa5, 0xe5, 0xdb, 0x27, 0x8d, 0xfd, 0xbb, 0x8d, 0x48, 0xc5, 0xd8, 0xba, 0xd4, 0xba, 0xc3, 0x97,
	0x08, 0xb1, 0x78, 0x42, 0x65, 0x6c, 0x67, 0xef, 0xac, 0xad, 0x30, 0xf8, 0x14, 0xb5, 0x17, 0x90,
	0xc5, 0x20, 0xbd, 0xa9, 0x1e, 0x19, 0xc7, 0x24, 0x70, 0xb6, 0x60, 0x22, 0xf3, 0x8e, 0xbe, 0x63,
	0x3c, 0x44, 0xbb, 0x31, 0xd5, 0xf0, 0x90, 0x8c, 0x99, 0xd4, 0x4b, 0x6f, 0x68, 0x95, 0xc2, 0x04,
	0x75, 0x68, 0x1c, 0x4b, 0x50, 0xca, 0xda, 0xd9, 0x0b, 0x4b, 0x68, 0xdc, 0xce, 0x39, 0x8d, 0xde,
	0x93, 0x3b, 0xee, 0xb4, 0x54, 0x39, 0xb3, 0x77, 0x2e, 0xc5, 0x0b, 0x33, 0xa3, 0xec, 0xba, 0xbd,
	0x4b, 0x6c, 0xfa, 0x99, 0x73, 0x21, 0xe2, 0x3b, 0x29, 0x8a, 0xdc, 0xdb, 0x53, 0x61, 0x4c, 0xff,
	0x52, 0x13, 0x64, 0xf9, 0xa6, 0xd4, 0x16, 0xbf, 0x92, 0x5d, 0x8f, 0x5f, 0x31, 0x46, 0xad, 0x88,
	0xe9, 0x37, 0xb2, 0x67, 0x19, 0xfb, 0x8d, 0xcf, 0x51, 0xef, 0x19, 0x78, 0x21, 0xe9, 0x92, 0x66,
	0x64, 0xdf, 0x06, 0x56, 0x84, 0xa9, 0x26, 0x36, 0xb3, 0x65, 0x91, 0x26, 0x7d, 0x57, 0x4d, 0x89,
	0xf1, 0xd7, 0xa8, 0x9f, 0x52, 0x29, 0x19, 0x5d, 0xc0, 0xa3, 0xa6, 0xba, 0x50, 0xe4, 0xc0, 0xae,
	0x58, 0x63, 0x4d, 0xd7, 0x7e, 0xe6, 0xce, 0xdb, 0x43, 0xd7, 0x75, 0x95, 0x33, 0x9d, 0x89, 0x28,
	0x2a, 0x72, 0x7b, 0x83, 0x90, 0x23, 0xd7, 0xd9, 0x8a, 0x31, 0x53, 0x8f, 0x98, 0x66, 0x7f, 0x41,
	0xa6, 0x96, 0x2c, 0x27, 0xd8, 0x4d, 0xbd, 0x42, 0x99, 0x15, 0x4e, 0x71, 0x9a, 0xd2, 0x05, 0x90,
	0x2f, 0xdc, 0x8a, 0x0a, 0x65, 0xea, 0x55, 0x6c, 0x91, 0x51, 0x5d, 0x48, 0x70, 0x8b, 0x8e, 0x5d,
	0xbd, 0x75, 0xd6, 0x28, 0x29, 0xe0, 0x09, 0xf3, 0x8b, 0x4e, 0x9c, 0x52, 0x85, 0x32, 0x0e, 0xbf,
	0x80, 0x54, 0xa6, 0xd4, 0x53, 0x7b, 0xd8, 0x4a, 0x88, 0x0f, 0xd1, 0xf6, 0x93, 0x98, 0x93, 0x33,
	0x9b, 0x63, 0x3e, 0xcd, 0xae, 0x4f, 0x62, 0xfe, 0x13, 0xa8, 0x48, 0xb2, 0xdc, 0x76, 0x47, 0xdc,
	0xae, 0x75, 0xd6, 0x68, 0x26, 0x60, 0xab, 0x20, 0x5f, 0xba, 0x53, 0xe3, 0xa1, 0x89, 0xe4, 0x52,
	0xc4, 0x45, 0xa4, 0xc9, 0xc0, 0x45, 0x3c, 0xb4, 0x67, 0xb1, 0x22, 0xfc, 0x95, 0x3f, 0x8b, 0x2b,
	0xea, 0xf6, 0xdf, 0x06, 0x6a, 0xd9, 0xcb, 0x6f, 0x86, 0x0e, 0xd6, 0xef, 0xe9, 0x73, 0x77, 0x23,
	0x6c, 0xbe, 0xf6, 0x07, 0x17, 0x65, 0x74, 0xe3, 0x25, 0x1f, 0x6c, 0xe1, 0x1f, 0x50, 0xa7, 0xbc,
	0x59, 0x8f, 0x6b, 0x4a, 0x9e, 0x1d, 0x9c, 0xd4, 0x15, 0x3c, 0x1d, 0x6c, 0xe1, 0x47, 0x74, 0xf8,
	0xe1, 0xaf, 0x7b, 0xb1, 0x2e, 0x51, 0x0b, 0x0f, 0x2e, 0x3f, 0x68, 0xd5, 0xe2, 0xc1, 0xd6, 0xf8,
	0x0a, 0x9d, 0x30, 0x31, 0x32, 0x2f, 0xdc, 0x08, 0xfe, 0xa4, 0x69, 0xce, 0x41, 0xd9, 0x9c, 0x71,
	0xcf, 0xec, 0x3a, 0x33, 0x4f, 0xdd, 0xac, 0x31, 0x6f, 0xdb, 0x37, 0xef, 0xdb, 0xff, 0x02, 0x00,
	0x00, 0xff, 0xff, 0x29, 0x8e, 0xfb, 0x3a, 0x14, 0x07, 0x00, 0x00,
}

// Reference imports to suppress errors if they are not otherwise used.
var _ context.Context
var _ grpc.ClientConn

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
const _ = grpc.SupportPackageIsVersion4

// UserClient is the client API for User service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://godoc.org/google.golang.org/grpc#ClientConn.NewStream.
type UserClient interface {
	TokenValidation(ctx context.Context, in *RequestTokenValidation, opts ...grpc.CallOption) (*ResponseTokenValidation, error)
	GetUser(ctx context.Context, in *RequestGetUser, opts ...grpc.CallOption) (*ResponseGetUser, error)
	GetCivilRegistry(ctx context.Context, in *RequestGetCivilRegistry, opts ...grpc.CallOption) (*ResponseGetCivilRegistry, error)
}

type userClient struct {
	cc *grpc.ClientConn
}

func NewUserClient(cc *grpc.ClientConn) UserClient {
	return &userClient{cc}
}

func (c *userClient) TokenValidation(ctx context.Context, in *RequestTokenValidation, opts ...grpc.CallOption) (*ResponseTokenValidation, error) {
	out := new(ResponseTokenValidation)
	err := c.cc.Invoke(ctx, "/user.User/TokenValidation", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetUser(ctx context.Context, in *RequestGetUser, opts ...grpc.CallOption) (*ResponseGetUser, error) {
	out := new(ResponseGetUser)
	err := c.cc.Invoke(ctx, "/user.User/GetUser", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *userClient) GetCivilRegistry(ctx context.Context, in *RequestGetCivilRegistry, opts ...grpc.CallOption) (*ResponseGetCivilRegistry, error) {
	out := new(ResponseGetCivilRegistry)
	err := c.cc.Invoke(ctx, "/user.User/GetCivilRegistry", in, out, opts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// UserServer is the server API for User service.
type UserServer interface {
	TokenValidation(context.Context, *RequestTokenValidation) (*ResponseTokenValidation, error)
	GetUser(context.Context, *RequestGetUser) (*ResponseGetUser, error)
	GetCivilRegistry(context.Context, *RequestGetCivilRegistry) (*ResponseGetCivilRegistry, error)
}

// UnimplementedUserServer can be embedded to have forward compatible implementations.
type UnimplementedUserServer struct {
}

func (*UnimplementedUserServer) TokenValidation(ctx context.Context, req *RequestTokenValidation) (*ResponseTokenValidation, error) {
	return nil, status.Errorf(codes.Unimplemented, "method TokenValidation not implemented")
}
func (*UnimplementedUserServer) GetUser(ctx context.Context, req *RequestGetUser) (*ResponseGetUser, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetUser not implemented")
}
func (*UnimplementedUserServer) GetCivilRegistry(ctx context.Context, req *RequestGetCivilRegistry) (*ResponseGetCivilRegistry, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetCivilRegistry not implemented")
}

func RegisterUserServer(s *grpc.Server, srv UserServer) {
	s.RegisterService(&_User_serviceDesc, srv)
}

func _User_TokenValidation_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestTokenValidation)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).TokenValidation(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/TokenValidation",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).TokenValidation(ctx, req.(*RequestTokenValidation))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetUser_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetUser)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetUser(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetUser",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetUser(ctx, req.(*RequestGetUser))
	}
	return interceptor(ctx, in, info, handler)
}

func _User_GetCivilRegistry_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RequestGetCivilRegistry)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(UserServer).GetCivilRegistry(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: "/user.User/GetCivilRegistry",
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(UserServer).GetCivilRegistry(ctx, req.(*RequestGetCivilRegistry))
	}
	return interceptor(ctx, in, info, handler)
}

var _User_serviceDesc = grpc.ServiceDesc{
	ServiceName: "user.User",
	HandlerType: (*UserServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "TokenValidation",
			Handler:    _User_TokenValidation_Handler,
		},
		{
			MethodName: "GetUser",
			Handler:    _User_GetUser_Handler,
		},
		{
			MethodName: "GetCivilRegistry",
			Handler:    _User_GetCivilRegistry_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "platform/grpc/user/fiber.proto",
}
